config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :contacts

  root 'contacts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :name, presence: true
    validates :email, :nophone, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

    def index
        @contacts = Contact.order(created_at: :desc)
    end

    # GET /users/1 or /users/1.json
  def show
    # @contact = Contact.find(params[:id])
    # respond_to do |format|
    #   format.js
    # end
  end

  # GET /users/new
  def new
    @contact = Contact.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
        if @contact.save
            format.js
            format.html { redirect_to contact_url(@contact), notice: 'Kontak was successfully created.' }
            format.json { render :show, status: :created, location: @contact }
            
        else    
            format.js
            format.html { render :new, status: :unprocessable_entity}
            format.json { render json: @contact.errors, status: :unprocessable_entity}
        end
    end
end

     # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
        format.js
      else
        format.js
        format.html { render :edit, status: :unprocessable_entity}
        format.json { render json: @contact.errors, status: :unprocessable_entity}
        end
    end
end

# DELETE /users/1 or /users/1.json
def destroy
  @contact = Contact.find_by(id: params[:id])
  
  if @contact
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
      format.js
    end
  else
    flash[:error] = "Contact not found"
    redirect_to contacts_url
  end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
        params.require(:contact).permit(:name, :email, :nophone)
      end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact_row.html.erb
<tr id="contactRow_<%= contact.id %>">
  <td><%= contact.name %></td>
  <td><%= contact.email %></td>
  <td><%= contact.nophone %></td>
  <td>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Actions
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <li><%= link_to 'Show', contact, class: "dropdown-item", data: { bs_toggle: "modal", bs_target: "#showContactModal", remote: true } %></li>
        <li><%= link_to 'Edit', edit_contact_path(contact), class: "dropdown-item", data: 
        { bs_toggle: 'modal', bs_target: '#editContactModal', remote: true } %></li>
        <li><%= link_to 'Destroy', contact, method: :delete, data: {confirm: 'Are you sure?', remote: true}, class: "dropdown-item" %></li>
      </ul>
    </div>
  </td>
</tr>

app/views/contacts/_error.html.erb
<% if contact.errors.any? %>
  <div id="error_explanation">
    <h6 class="text-danger"><%= pluralize(contact.errors.count, "error") %> prohibited this user from being saved:</h6>
    <% contact.errors.each do |error| %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong><%= error.full_message %></strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
  </div>
<% end %>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: false) do |form| %>
  <div class="modal-body">
    <div id="errorArea"></div>

    <div class="form-group mt-3">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group mt-3">
      <%= form.label :email %>
      <%= form.text_field :email, class: 'form-control' %>
    </div>

    <div class="form-group mt-3">
      <%= form.label :nophone %>
      <%= form.text_field :nophone, class: 'form-control' %>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary btn-lg close-modal" data-bs-dismiss="modal">Close</button>    
    <%= form.submit class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/contacts/_show.html.erb
<div class="modal-body">
  <div class="col-lg-12">

    <p>
    <strong>Here <%= @contact.name %> Contact Information</strong>
    </p>

    <p>
      <strong>Name:</strong>
      <%= contact.name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= contact.email %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= contact.nophone %>
    </p>

  </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary btn-lg close-modal" data-bs-dismiss="modal">Close</button>
</div>

app/views/contacts/create.js.erb
<% if @contact.errors.any? %>
  $("#errorArea").html("<%= escape_javascript render('error', contact: @contact)%>")
<% else %>
  $("#contactsTable").prepend("<%= escape_javascript render('contact_row', contact: @contact)%>");
  $(".close-modal").click();
<% end %>

app/views/contacts/destroy.js.erb
$("#contactRow_<%= @contact.id %>").remove();

app/views/contacts/edit.js.erb
$("#editContactForm").html("<%= escape_javascript render('form', contact: @contact)%>");

app/views/contacts/index.html.erb
<div class = "container">
    <div class = "row">
        <div class = "col-lg-12 md-auto">
        <h1>Kontakan</h1>

            <%= link_to 'New Kontak', new_contact_path, class: "btn btn-primary btn-lg mb-4", data: { bs_toggle: 'modal', bs_target: '#newContactModal', remote: true } %>

            <table id="contact" class="table table-bordered">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Telepon</th>
                    <th></th>
                </tr>
                </thead>

                <tbody id="contactsTable">
                    <% @contacts.each do |contact| %>
                    <%= render 'contact_row', contact: contact %>
                <% end %>
                </tbody>
            </table>

            <div clsss = "card shadow mt-5">
                <div class = "card-body">
                    <p class="lead fw-bold"> Apikasi penyimpanan kontak dan kenalanmu </p>
                     <%= link_to "More", "javascript:void(0)", class: "btn btn-primary btn-lg" %>
                     <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        Launch demo modal</button>

                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="newContactModal" tabindex="-1" aria-labelledby="newContactModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newContactModalLabel">Create New</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="newContactForm">
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="editContactModal" tabindex="-1" aria-labelledby="editContactModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editContactModalLabel">Edit Kontak</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="editContactForm">
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="showContactModal" tabindex="-1" aria-labelledby="showContactModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="showContactModalLabel">Kontak Detail</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="showContactDetails">
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/contacts/new.js.erb
<%# $("#newContactForm").html("<%= escape_javascript render('form', contact: @contact)%>"); %>

$('#newContactModal #newContactForm').html('<%= j render partial: "form", locals: { contact: @contact } %>');

$('#newContactModal #newContactForm').html("asdf");

app/views/contacts/show.js.erb
$("#showContactDetails").html("<%= escape_javascript render('show', contact: @contact)%>");

app/views/contacts/update.js.erb
<% if @contact.errors.any? %>
  $("#errorArea").html("<%= escape_javascript render('error', contact: @contact)%>")
<% else %>
  $("#contactRow_<%= @contact.id %>").replaceWith("<%= escape_javascript render('contact_row', contact: @contact)%>");
  $(".close-modal").click();
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KontakApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <<%= render "shared/header" %>>
    <%= yield %>
    <<%= render "shared/footer" %>>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="mt-5 bg-primary p-3">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <p class="text-white">Kontakan App</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Kontak Kontakan</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Contacts', contacts_path, class: "nav-link active" %>
      </ul>
    </div>
  </div>
</nav>